# Generated by Django 6.0.5 on 2026-08-24 16:21

import django.db.models.deletion
from django.db import migrations, models

import gpx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GpxTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(max_length=255, upload_to=gpx.models.gpx_upload_path)),
                ("points", models.JSONField()),
                ("min_latitude", models.FloatField()),
                ("min_longitude", models.FloatField()),
                ("max_latitude", models.FloatField()),
                ("max_longitude", models.FloatField()),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
    ]
