# Generated by Django 6.0.5 on 2026-08-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpx", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpxtrack",
            name="distance_meters",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpxtrack",
            name="duration_seconds",
            field=models.FloatField(
                blank=True,
                help_text=(
                    "Recorded time: the sum of each GPX segment's own span. Gaps between "
                    "segments — including overnight gaps on a multi-day tour — are "
                    "excluded, so this is not wall-clock elapsed time."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gpxtrack",
            name="elevation_gain_meters",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpxtrack",
            name="elevation_loss_meters",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
