# Generated by Django 6.0.8 on 2026-09-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpx", "0003_backfill_gpxtrack_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpxtrack",
            name="ended_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last recorded GPS instant, or null if none was usable.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gpxtrack",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="First recorded GPS instant, or null if none was usable.",
                null=True,
            ),
        ),
    ]
