"""
Django settings for velo_log project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


def env_or(key: str, fallback: str) -> str:
    """Read an optional path-like env var, treating a blank value as unset.

    `env(key, default=...)` returns the default only when the key is *absent*; a key
    that is present but blank yields "". `.env.example` ships every optional key blank,
    so a verbatim copy would otherwise resolve to "" — which `FileSystemStorage` turns
    into `os.path.abspath("")`, the process CWD, silently writing uploads next to the
    source tree instead of the configured location.
    """
    return env(key, default="") or fallback


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "trips",
    "gpx",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "velo_log.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "velo_log.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": env_or("DB_PATH", str(BASE_DIR / "db.sqlite3")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# Media files (user uploads)
# https://docs.djangoproject.com/en/6.0/topics/files/

# Django replaces STORAGES wholesale rather than merging, so declaring "staticfiles"
# alone drops the "default" alias every FileField resolves through. The binding is lazy
# (it resolves on the first storage.save/url, not at startup), so nothing short of a real
# storage write catches its absence — see tests/test_media_storage.py.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Mirrors the DB_PATH idiom above: production points this at the mounted Railway Volume
# (/data/media, see DEPLOY.md) so uploads survive a redeploy. The local default sits
# inside the repo and is gitignored.
MEDIA_ROOT = env_or("MEDIA_ROOT", str(BASE_DIR / "media"))

# Must not be "/" — that is what an unset MEDIA_URL resolves to, and it collides with the
# root RedirectView in velo_log/urls.py. No URL is ever served from this prefix (uploaded
# files go through an ownership-scoped view); it exists so FileField.url is well-formed.
MEDIA_URL = "media/"

# Written out rather than inherited, so a later change to either is a visible diff.
# Both currently hold Django's own defaults.
# FILE_UPLOAD_MAX_MEMORY_SIZE is the in-memory vs TemporaryUploadedFile switchover for
# file fields. Keep it below the upload cap: a real multi-day tour GPX then spools to
# disk, which keeps the seek(0)-before-save contract on the tested path rather than the
# rare one.
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB
# DATA_UPLOAD_MAX_MEMORY_SIZE bounds non-file request data only; it does not apply to
# file-upload fields and is therefore no bound at all on a GPX upload.
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB


# Authentication
# https://docs.djangoproject.com/en/6.0/topics/auth/default/

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "trips:list"
LOGOUT_REDIRECT_URL = "login"

if not DEBUG:
    # Railway terminates TLS at a proxy in front of the app, so Django must be
    # told to trust that header — otherwise every request looks like plain HTTP.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    # Start low and raise once verified in production — a wrong HSTS value is
    # sticky in browsers for its full duration.
    SECURE_HSTS_SECONDS = 3600
