"""
Django settings for velo_log project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import logging
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


def env_or(key: str, fallback: str) -> str:
    """Read an optional path-like env var, treating a blank value as unset.

    `env(key, default=...)` returns the default only when the key is *absent*; a key
    that is present but blank yields "". A blank is easy to arrive at — a hand-edited
    `.env` keeping the key as a reminder, or a deploy environment that defines it empty
    — and for MEDIA_ROOT the result is silent: `FileSystemStorage` turns "" into
    `os.path.abspath("")`, the process CWD, writing uploads next to the source tree
    instead of the configured location.
    """
    return env(key, default="") or fallback


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "trips",
    "gpx",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "velo_log.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "velo_log.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": env_or("DB_PATH", str(BASE_DIR / "db.sqlite3")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Mirrors the TEMPLATES["DIRS"] convention above exactly: project-level, cross-cutting
# assets live at the repo root, app-namespaced assets inside the app that owns them.
# Without this entry the directory is invisible to collectstatic and to the static tag,
# so base.html's stylesheet would 404 in production while resolving fine in DEBUG.
STATICFILES_DIRS = [BASE_DIR / "static"]


# Media files (user uploads)
# https://docs.djangoproject.com/en/6.0/topics/files/

# Django replaces STORAGES wholesale rather than merging, so declaring "staticfiles"
# alone drops the "default" alias every FileField resolves through. The binding is lazy
# (it resolves on the first storage.save/url, not at startup), so nothing short of a real
# storage write catches its absence — see tests/test_media_storage.py.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Mirrors the DB_PATH idiom above: production points this at the mounted Railway Volume
# (/data/media, see DEPLOY.md) so uploads survive a redeploy. The local default sits
# inside the repo and is gitignored.
MEDIA_ROOT = env_or("MEDIA_ROOT", str(BASE_DIR / "media"))

# Must not be "/" — that is what an unset MEDIA_URL resolves to, and it collides with the
# root RedirectView in velo_log/urls.py. No URL is ever served from this prefix (uploaded
# files go through an ownership-scoped view); it exists so FileField.url is well-formed.
MEDIA_URL = "media/"

# Written out rather than inherited, so a later change to either is a visible diff.
# Both currently hold Django's own defaults.
# FILE_UPLOAD_MAX_MEMORY_SIZE is the in-memory vs TemporaryUploadedFile switchover for
# file fields. Keep it below the upload cap: a real multi-day tour GPX then spools to
# disk, which keeps the seek(0)-before-save contract on the tested path rather than the
# rare one.
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB
# DATA_UPLOAD_MAX_MEMORY_SIZE bounds non-file request data only; it does not apply to
# file-upload fields and is therefore no bound at all on a GPX upload.
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB


# Logging
# https://docs.djangoproject.com/en/6.0/topics/logging/


class _MediaRootDefaultFilter(logging.Filter):
    """Default a missing `media_root` field so the formatter can render it unconditionally.

    Most records through this handler (e.g. `logger.exception` calls with no `extra=`)
    never set `media_root`; without this, `{media_root}` in the format string would raise
    `KeyError` at format time for every one of them.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        if not hasattr(record, "media_root"):
            record.media_root = ""
        return True


# Named `velo_log_console`, not `console` — Django's own DEFAULT_LOGGING already
# registers a handler literally named `console` (gated by a `require_debug_true` filter,
# wired to the `django` logger). This project's LOGGING dict is applied via a second
# dictConfig call on top of Django's own; reusing the name `console` would reconfigure
# that same handler object in place, silently dropping its `require_debug_true` filter
# even though `django.*` loggers are meant to be left untouched below.
#
# The root (`""`) logger is deliberately given a handler too: `gpx/views.py` also logs
# via `logging.getLogger(__name__)` (`gpx.views`, not a descendant of `velo_log`), so it
# only reaches the console through root propagation.
#
# Known tradeoff: Django's own `"django"` logger does not set `propagate: False` (only
# `"django.server"` does), so once root has a handler, a `django`-logger record already
# handled by Django's own `console`/`mail_admins` handlers also reaches root and prints a
# second time, in this format instead of Django's. Accepted for this low-traffic personal
# project — the duplication is confined to `DEBUG=True` local dev, and avoiding it would
# mean giving `"django"` an explicit `propagate: False` (risking suppression of a
# framework message this project has no mandate to touch) or dropping the root handler
# (which would break `gpx.views`' coverage).
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "media_root_default": {"()": "velo_log.settings._MediaRootDefaultFilter"},
    },
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message} media_root={media_root}",
            "style": "{",
        },
    },
    "handlers": {
        "velo_log_console": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "formatter": "verbose",
            "filters": ["media_root_default"],
        },
    },
    "loggers": {
        "": {
            "handlers": ["velo_log_console"],
            "level": "INFO" if DEBUG else "WARNING",
        },
        "velo_log": {
            "handlers": ["velo_log_console"],
            "level": "INFO" if DEBUG else "WARNING",
            "propagate": False,
        },
    },
}


# Authentication
# https://docs.djangoproject.com/en/6.0/topics/auth/default/

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "trips:list"
LOGOUT_REDIRECT_URL = "login"

if not DEBUG:
    # Railway terminates TLS at a proxy in front of the app, so Django must be
    # told to trust that header — otherwise every request looks like plain HTTP.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    # Start low and raise once verified in production — a wrong HSTS value is
    # sticky in browsers for its full duration.
    SECURE_HSTS_SECONDS = 3600
